# Generated by Django 6.0.6 on 2026-06-24 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('soft', 'Soft')], default='light', max_length=20)),
                ('accent_color', models.CharField(choices=[('rose', 'Rose'), ('emerald', 'Emerald'), ('blue', 'Blue'), ('violet', 'Violet'), ('amber', 'Amber')], default='rose', max_length=20)),
                ('text_size', models.CharField(choices=[('normal', 'Normal'), ('large', 'Besar'), ('xl', 'Ekstra besar')], default='normal', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
