# Generated by Django 6.0.6 on 2026-06-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_public_uuids'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='media_file',
            field=models.FileField(blank=True, upload_to='question-media/'),
        ),
        migrations.AddField(
            model_name='question',
            name='media_type',
            field=models.CharField(choices=[('none', 'Tanpa media'), ('image', 'Gambar'), ('audio', 'Audio'), ('video', 'Video upload'), ('youtube', 'YouTube')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='media_url',
            field=models.URLField(blank=True),
        ),
    ]
