# Generated by Django 6.0.6 on 2026-06-25 09:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_ubt_ubtpackage_voucher_assigned_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ubt',
            name='passing_score',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.CreateModel(
            name='UBTAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('ubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.ubt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubt_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UBTQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('none', 'Tanpa media'), ('image', 'Gambar'), ('audio', 'Audio'), ('video', 'Video upload'), ('youtube', 'YouTube')], default='none', max_length=20)),
                ('media_file', models.FileField(blank=True, upload_to='ubt-question-media/')),
                ('media_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('ubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.ubt')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UBTChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='learning.ubtquestion')),
            ],
        ),
        migrations.CreateModel(
            name='UBTAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.ubtattempt')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.ubtchoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.ubtquestion')),
            ],
        ),
    ]
