# Generated by Django 6.0.6 on 2026-06-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_landingpagevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubt',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
