# Generated by Django 6.0.6 on 2026-07-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_blogpostread'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Gambar'), ('audio', 'Audio'), ('video', 'Video')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='choice',
            name='media_file',
            field=models.FileField(blank=True, upload_to='choice-media/'),
        ),
        migrations.AddField(
            model_name='choice',
            name='media_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='ubtchoice',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Gambar'), ('audio', 'Audio'), ('video', 'Video')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='ubtchoice',
            name='media_file',
            field=models.FileField(blank=True, upload_to='ubt-choice-media/'),
        ),
        migrations.AddField(
            model_name='ubtchoice',
            name='media_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ubtchoice',
            name='text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
