# Generated by Django 6.0.6 on 2026-07-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_choice_answer_type_choice_media_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ubtquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
