# Generated by Django 6.0.6 on 2026-07-07 22:47

from django.db import migrations, models
from django.utils import timezone


def mark_existing_active_users_verified(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('learning', 'UserProfile')
    verified_at = timezone.now()
    for user in User.objects.filter(is_staff=False, is_active=True):
        profile, _ = UserProfile.objects.get_or_create(user=user)
        if not profile.email_verified_at:
            profile.email_verified_at = verified_at
            profile.save(update_fields=['email_verified_at'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_question_is_active_ubtquestion_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_active_users_verified, noop_reverse),
    ]
