# Generated by Django 6.0.6 on 2026-07-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_userprofile_email_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagevisit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
